name: hyphen design
favicon: null
layout_spectrum: 0.0007
typography_spectrum: 0.29276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdff'
    - '#ffc29f'
    - '#ff8a80'
    - '#e72f57'
    - '#f3516a'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
